name: Run Nikon Scraper Every Hour

on:
  schedule:
    - cron: "0 * * * *"  # This runs the job every hour at minute 0
  workflow_dispatch:  # Allows manual triggers

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      run: |
        python nikon_scraper.py

    - name: Check if any product is in stock and update GitHub issue
      run: |
        # Assuming you have a Python script (send_github_notification.py) that checks the stock and sends a notification if needed
        python send_github_notification.py
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Pass the secret to the script

    - name: Check if any product is in stock and update GitHub issue
      run: |
        python send_github_notification.py
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        FROM_PASSWORD: ${{ secrets.FROM_PASSWORD }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}